/**
 * PostgreSQL-migrationer uden database (offline).
 *
 * Skemaet i prisma/postgres/schema.prisma er afledt af prisma/schema.prisma (se gen-pg-schema.ts).
 * Migrationer ligger i prisma/postgres/migrations og køres med `prisma migrate deploy` ved opstart.
 * `prisma/postgres/.last-migrated-schema.txt` er en kopi af skemaet som det så ud efter seneste migration;
 * forskellen mellem den og det nuværende skema er præcis de ændringer, der mangler en migration.
 *
 *   npm run prisma:pg:migration -- <navn>   # genererér skemaet, diff mod sidste migrerede tilstand, skriv ny migration
 *   npm run prisma:pg:check                 # fejl hvis skemaet er ude af sync ELLER en migration mangler
 *
 * Datatab: migrate diff genererer DROP/ALTER ved omdøbninger. Gennemlæs altid migration.sql før commit.
 */
import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { checkInSync, PG_SCHEMA, writeGenerated } from "./gen-pg-schema";

const ROOT = path.resolve(__dirname, "..");
export const MIGRATIONS_DIR = path.join(ROOT, "prisma/postgres/migrations");
export const LAST_MIGRATED = path.join(ROOT, "prisma/postgres/.last-migrated-schema.txt");
const EMPTY_MARKER = "-- This is an empty migration.";

function prismaBin() {
  return path.join(ROOT, "node_modules/.bin/prisma");
}

/** Kører `prisma migrate diff … --script` offline. DATABASE_URL skal kun findes (må være en dummy). */
export function diffScript(from: string | null, to: string): string {
  const args = ["migrate", "diff", ...(from ? ["--from-schema-datamodel", from] : ["--from-empty"]), "--to-schema-datamodel", to, "--script"];
  const res = spawnSync(prismaBin(), args, {
    cwd: ROOT,
    encoding: "utf8",
    env: { ...process.env, DATABASE_URL: process.env.DATABASE_URL?.startsWith("postgres") ? process.env.DATABASE_URL : "postgresql://offline:offline@localhost:5432/offline" },
  });
  if (res.status !== 0) throw new Error(`prisma migrate diff fejlede: ${(res.stderr || res.stdout).split("\n").slice(0, 5).join(" | ")}`);
  return res.stdout;
}

export function migrationNames(): string[] {
  if (!existsSync(MIGRATIONS_DIR)) return [];
  return readdirSync(MIGRATIONS_DIR, { withFileTypes: true }).filter((d) => d.isDirectory()).map((d) => d.name).sort();
}

/** Mangler der en migration til det nuværende PostgreSQL-skema? Returnerer SQL'en der mangler (tom = ingen). */
export function pendingMigrationSql(): string {
  if (!existsSync(LAST_MIGRATED)) throw new Error("prisma/postgres/.last-migrated-schema.txt mangler.");
  const script = diffScript(LAST_MIGRATED, PG_SCHEMA).trim();
  return script === EMPTY_MARKER ? "" : script;
}

function timestamp(d = new Date()) {
  return d.toISOString().replace(/\D/g, "").slice(0, 14);
}

function create(name: string) {
  if (!/^[a-z0-9_]{2,50}$/.test(name)) throw new Error("Migrationsnavn: små bogstaver, tal og _ (2-50 tegn).");
  writeGenerated(); // regenerér pg-skemaet fra kilden
  const first = migrationNames().length === 0;
  const script = diffScript(first ? null : LAST_MIGRATED, PG_SCHEMA);
  if (script.trim() === EMPTY_MARKER) {
    console.log("[pg-migration] Ingen skemaændringer siden sidste migration — intet at gøre.");
    return;
  }
  const dir = path.join(MIGRATIONS_DIR, `${timestamp()}_${name}`);
  mkdirSync(dir, { recursive: true });
  writeFileSync(path.join(dir, "migration.sql"), script);
  writeFileSync(path.join(MIGRATIONS_DIR, "migration_lock.toml"), "# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = \"postgresql\"\n");
  copyFileSync(PG_SCHEMA, LAST_MIGRATED);
  console.log(`[pg-migration] skrev ${path.relative(ROOT, dir)}/migration.sql — gennemlæs den før commit.`);
}

function check() {
  const sync = checkInSync();
  if (!sync.ok) throw new Error(sync.reason);
  if (migrationNames().length === 0) throw new Error("Ingen PostgreSQL-migrationer i prisma/postgres/migrations.");
  const lock = path.join(MIGRATIONS_DIR, "migration_lock.toml");
  if (!existsSync(lock)) throw new Error("prisma/postgres/migrations/migration_lock.toml mangler.");
  const pending = pendingMigrationSql();
  if (pending) throw new Error("Skemaet har ændringer uden migration — kør: npm run prisma:pg:migration -- <navn>");
  console.log("[pg-migration] skema og migrationer er i sync.");
}

function main() {
  const [cmd] = process.argv.slice(2);
  try {
    if (cmd === "--check") check();
    else if (cmd) create(cmd);
    else throw new Error("Brug: npm run prisma:pg:migration -- <navn>   |   --check");
  
  } catch (err) {
    console.error(`[pg-migration] ${(err as Error).message}`);
    process.exit(1);
  }
}

if (path.basename(process.argv[1] ?? "") === "pg-migration.ts") main();
