export interface NetworkSiteArticleSeed {
  slug: string;
  titel: string;
  manchet: string;
  sectionSlug: string;
  areaSlug: string;
  authorIndex: number;
  mediaId: string;
  pinned?: boolean;
  breaking?: boolean;
  indholdstype: "Uafhængig" | "Partner" | "Sponsoreret" | "Brugerindsendt" | "AI-assisteret" | "PR";
  marking?: Record<string, unknown>;
  debatLabel?: string;
  daysAgo: number;
  hoursAgo?: number;
  hasQuoteWithSource?: boolean;
}

export interface NetworkSiteConfig {
  id: string;
  navn: string;
  domaene: string;
  kommune: string;
  tagline: string;
  colors: {
    accent: string;
    accentStrong: string;
    accentSoft: string;
    onAccent: string;
  };
  sideTekster: {
    omMediet: string;
    principper: string;
    kontakt: string;
  };
  areas: Array<{ navn: string; slug: string; lat: number; lng: number }>;
  authors: Array<{
    id: string;
    navn: string;
    slug: string;
    type: "Fast" | "Freelance";
    bio: string;
    avatar: string;
    email: string;
  }>;
  organizations: Array<{
    id: string;
    navn: string;
    branche: string;
    kontakt: string;
    aftaleId: string;
    aftalePris: number;
  }>;
  articles: NetworkSiteArticleSeed[];
}

export const ALL_NETWORK_SITES_INFO = [
  { navn: "SlagelseLokalt", domaene: "slagelselokalt.dk", by: "Slagelse" },
  { navn: "NæstvedLokalt", domaene: "naestvedlokalt.dk", by: "Næstved" },
  { navn: "HolbækLokalt", domaene: "holbaeklokalt.dk", by: "Holbæk" },
  { navn: "RingstedLokalt", domaene: "ringstedlokalt.dk", by: "Ringsted" },
  { navn: "KøgeLokalt", domaene: "koegelokalt.dk", by: "Køge" },
  { navn: "RoskildeLokalt", domaene: "roskildelokalt.dk", by: "Roskilde" },
];

export const NETWORK_SITES: NetworkSiteConfig[] = [
  // ─── 1. NÆSTVED ─────────────────────────────────────────────────────────
  {
    id: "naestved-site",
    navn: "NæstvedLokalt",
    domaene: "naestvedlokalt.dk",
    kommune: "Næstved",
    tagline: "Din uafhængige stemme i Næstved, Karrebæksminde og omegn",
    colors: {
      accent: "#1F5663", // Fjord
      accentStrong: "#153C45",
      accentSoft: "#D9E8EB",
      onAccent: "#FFFFFF",
    },
    sideTekster: {
      omMediet:
        "NæstvedLokalt er et lokalt og uafhængigt nyhedsmedie for Næstved Kommune. Vi dækker byrådet, det blomstrende kulturliv, erhvervsudviklingen på havnen og hverdagen i stationsbyerne og ved kysten.",
      principper:
        "Vi overholder de presseetiske regler og mærker alt betalt, sponsoreret og AI-assisteret indhold 100% gennemskueligt.",
      kontakt:
        "Skriv til redaktionen på redaktion@naestvedlokalt.dk eller ring på 55 70 00 00.",
    },
    areas: [
      { navn: "Næstved By", slug: "naestved-by", lat: 55.2299, lng: 11.7609 },
      { navn: "Karrebæksminde", slug: "karrebaeksminde", lat: 55.1878, lng: 11.6494 },
      { navn: "Fuglebjerg", slug: "fuglebjerg", lat: 55.3056, lng: 11.5456 },
      { navn: "Glumsø", slug: "glumsoe", lat: 55.3547, lng: 11.6881 },
      { navn: "Fensmark", slug: "fensmark", lat: 55.2803, lng: 11.8089 },
      { navn: "Holme-Olstrup", slug: "holme-olstrup", lat: 55.26, lng: 11.8483 },
      { navn: "Mogenstrup", slug: "mogenstrup", lat: 55.1969, lng: 11.8592 },
      { navn: "Tappernøje", slug: "tappernoeje", lat: 55.1764, lng: 11.9703 },
    ],
    authors: [
      {
        id: "author-naestved-morten",
        navn: "Morten Kaas",
        slug: "morten-kaas",
        type: "Fast",
        bio: "Ansvarshavende lokalredaktør på NæstvedLokalt med fokus på byråd og havn.",
        avatar: "/avatars/carsten.svg",
        email: "redaktoer@naestved.test",
      },
      {
        id: "author-naestved-camilla",
        navn: "Camilla Schrøder",
        slug: "camilla-schroeder",
        type: "Fast",
        bio: "Kultur- og samfundsreporter med særligt kendskab til kystlivet i Karrebæksminde.",
        avatar: "/avatars/rikke.svg",
        email: "camilla@naestved.test",
      },
      {
        id: "author-naestved-rasmus",
        navn: "Rasmus Krogh",
        slug: "rasmus-krogh",
        type: "Freelance",
        bio: "Freelancejournalist med dækning af erhverv og Næstved Boldklub.",
        avatar: "/avatars/jonas.svg",
        email: "journalist@naestved.test",
      },
    ],
    organizations: [
      {
        id: "org-naestved-erhverv",
        navn: "Næstved Erhvervsforening",
        branche: "Erhvervsnetværk",
        kontakt: "kontakt@naestvederhverv.dk",
        aftaleId: "sa-naestved-erhverv",
        aftalePris: 30000,
      },
    ],
    articles: [
      {
        slug: "naestved-havneudvidelse-skaber-200-nye-groenne-arbejdspladser",
        titel: "Historisk havneudvidelse i Næstved skal skabe 200 nye grønne arbejdspladser",
        manchet: "Byrådet har enstemmigt godkendt anlæggelsen af en ny multifunktionskaj ved Næstved Havn med fokus på genanvendelse og maritim transport.",
        sectionSlug: "byggeri-og-ejendomme",
        areaSlug: "naestved-by",
        authorIndex: 0,
        mediaId: "media-erhverv",
        pinned: true,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 0,
        hoursAgo: 2,
      },
      {
        slug: "karrebaeksminde-klaer-paa-til-aarets-stoerste-fiskefestival",
        titel: "Trafikvarsel ved Karrebæksminde: Græshoppebroen spærres kortvarigt under årets fiskefestival",
        manchet: "Over 8.000 besøgende forventes til weekendens traditionsrige fejring af kystkultur og lokale råvarer ved kanalen.",
        sectionSlug: "trafik",
        areaSlug: "karrebaeksminde",
        authorIndex: 1,
        mediaId: "media-trafik",
        pinned: false,
        breaking: true,
        indholdstype: "Uafhængig",
        daysAgo: 0,
        hoursAgo: 1,
      },
      {
        slug: "groennegades-kaserne-kulturcenter-slaar-publikumsrekord",
        titel: "Grønnegades Kaserne Kulturcenter melder om rekordomsætning og 65.000 gæster",
        manchet: "Kulturcentret oplever markant vækst i teater-, koncert- og comedytilbud på tværs af hele Sydsjælland.",
        sectionSlug: "musik",
        areaSlug: "naestved-by",
        authorIndex: 1,
        mediaId: "media-kultur",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 1,
      },
      {
        slug: "naestved-boldklub-henter-sejr-i-topopgoer-paa-tintshop-park",
        titel: "Næstved Boldklub sejrer i intens topkamp: 'Fællesskabet bar os hjem'",
        manchet: "En scoring i overtiden sikrede de grønblusede tre vigtige point i oprykningsspillet foran 2.400 tilskuere.",
        sectionSlug: "fodbold",
        areaSlug: "naestved-by",
        authorIndex: 2,
        mediaId: "media-sport",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 2,
      },
      {
        slug: "glumsoe-biograf-og-kulturhus-kaaret-til-aarets-lokalinitiativ",
        titel: "Frivillige i Glumsø hædret: Biograf og kulturhus kåret som årets sydsjællandske initiativ",
        manchet: "Mere end 60 frivillige driver den lokale biograf, der nu udvider med caféaftener og debatarrangementer.",
        sectionSlug: "frivillige",
        areaSlug: "glumsoe",
        authorIndex: 1,
        mediaId: "media-forening",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 3,
      },
      {
        slug: "fensmark-faar-ny-daginstitution-med-naturprofil-og-udekoekken",
        titel: "Byggeriet af ny integreret daginstitution i Fensmark går i gang før tid",
        manchet: "Børnene får base tæt på Holmegaard Mose med fokus på udeliv, bevægelse og bæredygtighed.",
        sectionSlug: "skole-og-boern",
        areaSlug: "fensmark",
        authorIndex: 0,
        mediaId: "media-skole",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 4,
      },
      {
        slug: "karrebaeksminde-roegeri-investerer-i-moderne-solcelleanlaeg",
        titel: "Traditionsrigt røgeri ved Enø Kanal satser på 100% grøn strøm til produktionen",
        manchet: "Med støtte fra lokal erhvervspulje reducerer Karrebæksminde Røgeri sit energiforbrug markant.",
        sectionSlug: "handel",
        areaSlug: "karrebaeksminde",
        authorIndex: 2,
        mediaId: "media-erhverv",
        pinned: false,
        breaking: false,
        indholdstype: "Partner",
        marking: {
          sponsor: "Næstved Erhvervsforening",
          labelTekst: "Finansieret af Næstved Erhvervsforening",
          aftaleId: "sa-naestved-erhverv",
        },
        daysAgo: 5,
      },
      {
        slug: "overblik-det-besluttede-naestved-byraad-om-skolebudgettet",
        titel: "Dagens overblik: Næstved Byråd tilfører 14 millioner ekstra til folkeskolen",
        manchet: "Gennemgang af de væsentligste forligspunkter fra tirsdagens ordinære byrådsmøde på Rådhuset.",
        sectionSlug: "politik",
        areaSlug: "naestved-by",
        authorIndex: 0,
        mediaId: "media-byraad",
        pinned: false,
        breaking: false,
        indholdstype: "AI-assisteret",
        marking: {
          godkendtAf: "Morten Kaas",
          kilder: [
            "https://naestved.dk/politik/dagsordener/byraad/2026-09-29",
            "Næstved Byrådssekretariat",
          ],
        },
        hasQuoteWithSource: true,
        daysAgo: 0,
        hoursAgo: 6,
      },
      {
        slug: "debat-bevar-det-aabne-land-mellem-fuglebjerg-og-sandved",
        titel: "Debat: Vi må ikke kvæle landsbyerne med uplanlagte solcelleparker",
        manchet: "Den grønne omstilling er vigtig, men borgerinddragelsen i Fuglebjerg og Sandved har haltet alvorligt bagefter.",
        sectionSlug: "kommentarer",
        areaSlug: "fuglebjerg",
        authorIndex: 1,
        mediaId: "media-debat",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        debatLabel: "Kommentar",
        daysAgo: 6,
      },
      {
        slug: "indsendt-tappernoeje-borgerforening-inviterer-til-faellesspisning",
        titel: "Fra borgerne: Tappernøje Forsamlingshus genopliver den ugentlige fællesspisning",
        manchet: "Alle generationer er velkomne til langbordsmiddag med lokale råvarer den første onsdag i hver måned.",
        sectionSlug: "lokalraad",
        areaSlug: "tappernoeje",
        authorIndex: 2,
        mediaId: "media-forening",
        pinned: false,
        breaking: false,
        indholdstype: "Brugerindsendt",
        marking: {
          afsender: "Tappernøje Borgerforening v/ Grethe Larsen",
        },
        daysAgo: 7,
      },
    ],
  },

  // ─── 2. HOLBÆK ──────────────────────────────────────────────────────────
  {
    id: "holbaek-site",
    navn: "HolbækLokalt",
    domaene: "holbaeklokalt.dk",
    kommune: "Holbæk",
    tagline: "Uafhængig lokaljournalistik fra Isefjorden til det åbne Vestsjælland",
    colors: {
      accent: "#4F5B1E", // Mos
      accentStrong: "#384114",
      accentSoft: "#E7EDD5",
      onAccent: "#FFFFFF",
    },
    sideTekster: {
      omMediet:
        "HolbækLokalt er det digitale nyhedsmedie for hele Holbæk Kommune — fra fjordbyen Holbæk til Orø og oplandets aktive lokalsamfund.",
      principper:
        "Vores journalistik er uafhængig af partipolitiske og kommercielle interesser. Betalt indhold er altid tydeligt deklareret.",
      kontakt:
        "Kontakt redaktionen på redaktion@holbaeklokalt.dk eller telefon 59 40 00 00.",
    },
    areas: [
      { navn: "Holbæk By", slug: "holbaek-by", lat: 55.7175, lng: 11.7139 },
      { navn: "Jyderup", slug: "jyderup", lat: 55.6569, lng: 11.4181 },
      { navn: "Tølløse", slug: "toelloese", lat: 55.6111, lng: 11.7708 },
      { navn: "Svinninge", slug: "svinninge", lat: 55.7208, lng: 11.4589 },
      { navn: "Vipperød", slug: "vipperoed", lat: 55.6683, lng: 11.7417 },
      { navn: "Regstrup", slug: "regstrup", lat: 55.6706, lng: 11.6033 },
      { navn: "Mørkøv", slug: "moerkoev", lat: 55.6489, lng: 11.5167 },
      { navn: "Orø", slug: "oroe", lat: 55.7667, lng: 11.8167 },
    ],
    authors: [
      {
        id: "author-holbaek-signe",
        navn: "Signe Barfod",
        slug: "signe-barfod",
        type: "Fast",
        bio: "Ansvarshavende redaktør på HolbækLokalt med blik for fjordens liv og byrådspolitik.",
        avatar: "/avatars/rikke.svg",
        email: "redaktoer@holbaek.test",
      },
      {
        id: "author-holbaek-jacob",
        navn: "Jacob Bentsen",
        slug: "jacob-bentsen",
        type: "Fast",
        bio: "Erhvervs- og samfundsreporter med base i Ahlgade og Holbæk Havn.",
        avatar: "/avatars/carsten.svg",
        email: "jacob@holbaek.test",
      },
      {
        id: "author-holbaek-line",
        navn: "Line Hesselbjerg",
        slug: "line-hesselbjerg",
        type: "Freelance",
        bio: "Lokalreporter med særlig kærlighed til Orø, Skarridsø og det vestsjællandske kulturliv.",
        avatar: "/avatars/mette.svg",
        email: "journalist@holbaek.test",
      },
    ],
    organizations: [
      {
        id: "org-holbaek-erhverv",
        navn: "Holbæk Erhvervsforum",
        branche: "Erhvervssammenslutning",
        kontakt: "kontakt@holbaekerhverv.dk",
        aftaleId: "sa-holbaek-erhverv",
        aftalePris: 30000,
      },
    ],
    articles: [
      {
        slug: "holbaek-fjord-nyt-maritimt-center-aabner-paa-havnen",
        titel: "Nyt maritimt center på Holbæk Havn åbner: 'Fjorden skal gøres tilgængelig for alle'",
        manchet: "Træskibe, kajakker og havbiologi samles i et nyt bæredygtigt træbyggeri, der binder bykernen sammen med fjorden.",
        sectionSlug: "kunst-og-museer",
        areaSlug: "holbaek-by",
        authorIndex: 0,
        mediaId: "media-havn",
        pinned: true,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 0,
        hoursAgo: 2,
      },
      {
        slug: "oroe-faergen-indsaetter-ekstra-afgange-i-hoejsaesonen",
        titel: "Orøfærgen udvider køreplanen: Flere aftenafgange sikrer pendlere og turister",
        manchet: "Holbæk Kommune og færgeselskabet imødekommer øboernes mangeårige ønske om mere fleksible overfarter.",
        sectionSlug: "trafik",
        areaSlug: "oroe",
        authorIndex: 2,
        mediaId: "media-trafik",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 1,
      },
      {
        slug: "jyderup-erhvervspark-tiltraekker-innovative-groenne-virksomheder",
        titel: "Jyderup Erhvervspark oplever boom: Tre nye produktionsvirksomheder rykker ind",
        manchet: "Nærheden til Skovvejen og motorvejsforbindelsen gør Jyderup til et attraktivt knudepunkt i Vestsjælland.",
        sectionSlug: "byggeri-og-ejendomme",
        areaSlug: "jyderup",
        authorIndex: 1,
        mediaId: "media-erhverv",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 2,
      },
      {
        slug: "holbaek-b-og-i-klar-til-saesonpremiere-paa-holbaek-sportsby",
        titel: "Holbæk B&I klar til brag i Sportsbyen: 1.800 tilskuere ventes til lokalopgør",
        manchet: "Træneren melder om fuld trup og højt humør før lørdagens topopgør i Danmarksserien mod Avarta.",
        sectionSlug: "fodbold",
        areaSlug: "holbaek-by",
        authorIndex: 1,
        mediaId: "media-sport",
        pinned: false,
        breaking: true,
        indholdstype: "Uafhængig",
        daysAgo: 0,
        hoursAgo: 1,
      },
      {
        slug: "toelloese-faar-nyt-kulturhus-i-den-gamle-stationsbygning",
        titel: "Frivillige kræfter i Tølløse omdanner stationsbygningen til levende kulturhus",
        manchet: "Projektet har modtaget 1,2 millioner kroner fra lokale fonde og åbner med café og kunstnerværksteder.",
        sectionSlug: "kulturforeninger",
        areaSlug: "toelloese",
        authorIndex: 2,
        mediaId: "media-forening",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 3,
      },
      {
        slug: "skarridsoe-faar-ny-handicapvenlig-natursti-hele-vejen-rundt",
        titel: "Naturstyrelsen etablerer 8 km sammenhængende sti rundt om Skarridsø",
        manchet: "Den nye rute giver fuglekiggere og naturelskere uhindret adgang til fredede vådområder og skovstrækninger.",
        sectionSlug: "natur-og-klima",
        areaSlug: "jyderup",
        authorIndex: 2,
        mediaId: "media-natur",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 4,
      },
      {
        slug: "holbaek-bryghus-udvider-eksporten-til-nordiske-naboer",
        titel: "Lokalt mikrobryggeri fordobler kapaciteten og sender Holbæk-øl til Sverige og Norge",
        manchet: "Investering i nye gæringstanke giver bryghuset mulighed for at nå ud til specialbutikker i hele Norden.",
        sectionSlug: "handel",
        areaSlug: "holbaek-by",
        authorIndex: 1,
        mediaId: "media-erhverv",
        pinned: false,
        breaking: false,
        indholdstype: "Partner",
        marking: {
          sponsor: "Holbæk Erhvervsforum",
          labelTekst: "Finansieret af Holbæk Erhvervsforum",
          aftaleId: "sa-holbaek-erhverv",
        },
        daysAgo: 5,
      },
      {
        slug: "overblik-det-besluttede-holbaek-byraad-om-klimatilpasning",
        titel: "Dagens overblik: Holbæk Byråd afsætter 28 millioner til sikring mod skybrud",
        manchet: "Gennemgang af de vedtagne kystsikringsprojekter for Ahlgade, havnefronten og Vipperød bæk.",
        sectionSlug: "politik",
        areaSlug: "holbaek-by",
        authorIndex: 0,
        mediaId: "media-byraad",
        pinned: false,
        breaking: false,
        indholdstype: "AI-assisteret",
        marking: {
          godkendtAf: "Signe Barfod",
          kilder: [
            "https://holbaek.dk/politik/byraad/referat-2026-09",
            "Holbæk Byrådssekretariat",
          ],
        },
        hasQuoteWithSource: true,
        daysAgo: 0,
        hoursAgo: 8,
      },
      {
        slug: "debat-holbaek-skal-bevare-sin-historiske-koebstadsidentitet",
        titel: "Leder: Vi må ikke ofre Ahlgades charme for hurtige højhuse",
        manchet: "Holbæk har en sjæl som handels- og fjordby. Nybyggeri skal ske med respekt for byens arkitektoniske rødder.",
        sectionSlug: "leder",
        areaSlug: "holbaek-by",
        authorIndex: 0,
        mediaId: "media-debat",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        debatLabel: "Leder",
        daysAgo: 6,
      },
      {
        slug: "indsendt-vipperoed-grundejerforening-arrangerer-traeplantningsdag",
        titel: "Fra borgerne: Vipperød planter 500 nye hjemmehørende træer i lokalt grønt bælte",
        manchet: "Borgere i alle aldre mødte op med spader for at skabe bedre vilkår for fugle og insekter.",
        sectionSlug: "frivillige",
        areaSlug: "vipperoed",
        authorIndex: 2,
        mediaId: "media-natur",
        pinned: false,
        breaking: false,
        indholdstype: "Brugerindsendt",
        marking: {
          afsender: "Vipperød Grundejerforening",
        },
        daysAgo: 8,
      },
    ],
  },

  // ─── 3. RINGSTED ────────────────────────────────────────────────────────
  {
    id: "ringsted-site",
    navn: "RingstedLokalt",
    domaene: "ringstedlokalt.dk",
    kommune: "Ringsted",
    tagline: "Nyheder fra hjertet af Sjælland — lokalt, uafhængigt og tæt på dig",
    colors: {
      accent: "#8A5A00", // Okker
      accentStrong: "#664200",
      accentSoft: "#F5ECCF",
      onAccent: "#FFFFFF",
    },
    sideTekster: {
      omMediet:
        "RingstedLokalt er midtpunktet for lokal journalistik i Ringsted Kommune med fokus på byens udvikling, handelsliv og foreningskræfter.",
      principper:
        "Vi værner om kildebeskyttelse og gennemskuelighed i overensstemmelse med god presseskik.",
      kontakt:
        "Kontakt redaktionen på redaktion@ringstedlokalt.dk eller telefon 57 60 00 00.",
    },
    areas: [
      { navn: "Ringsted By", slug: "ringsted-by", lat: 55.4428, lng: 11.7917 },
      { navn: "Benløse", slug: "benloese", lat: 55.4639, lng: 11.8156 },
      { navn: "Jystrup", slug: "jystrup", lat: 55.5186, lng: 11.8708 },
      { navn: "Vetterslev", slug: "vetterslev", lat: 55.3906, lng: 11.7881 },
      { navn: "Kværkeby", slug: "kvaerkeby", lat: 55.4414, lng: 11.8819 },
      { navn: "Høm", slug: "hoem", lat: 55.4158, lng: 11.7764 },
      { navn: "Sigersted", slug: "sigersted", lat: 55.4192, lng: 11.7144 },
      { navn: "Vigersted", slug: "vigersted", lat: 55.4853, lng: 11.8906 },
    ],
    authors: [
      {
        id: "author-ringsted-henrik",
        navn: "Henrik Bang",
        slug: "henrik-bang",
        type: "Fast",
        bio: "Lokalredaktør på RingstedLokalt med fokus på bymidte, erhverv og transportknudepunkt.",
        avatar: "/avatars/carsten.svg",
        email: "redaktoer@ringsted.test",
      },
      {
        id: "author-ringsted-katrine",
        navn: "Katrine Toft",
        slug: "katrine-toft",
        type: "Freelance",
        bio: "Lokalreporter med særligt fokus på landsbysamfund, kulturarv og foreningsliv i Ringsted Kommune.",
        avatar: "/avatars/mette.svg",
        email: "journalist@ringsted.test",
      },
    ],
    organizations: [
      {
        id: "org-ringsted-erhverv",
        navn: "Ringsted Erhvervsråd",
        branche: "Erhvervsråd",
        kontakt: "info@ringstederhverv.dk",
        aftaleId: "sa-ringsted-erhverv",
        aftalePris: 30000,
      },
    ],
    articles: [
      {
        slug: "ringsted-bymidte-stort-udviklingsprojekt-omkring-torvet-vedtaget",
        titel: "Omfattende fornyelse af Ringsted Torv og Sct. Bendts Kirkeplads vedtaget",
        manchet: "Et nyt byrum med mere vand, udeservering og færre biler skal gøre Ringsteds historiske hjerte til samlingspunkt for hele Midtsjælland.",
        sectionSlug: "bolig-og-byudvikling",
        areaSlug: "ringsted-by",
        authorIndex: 0,
        mediaId: "media-byraad",
        pinned: true,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 0,
        hoursAgo: 3,
      },
      {
        slug: "ringsted-outlet-udvider-med-ti-nye-butikker-og-spisesteder",
        titel: "Ringsted Outlet investerer 75 millioner: Udvider med ti nye internationale brands",
        manchet: "Det populære shoppingcenter tiltrækker årligt over to millioner kunder og udvider nu sit samlede butiksareal.",
        sectionSlug: "handel",
        areaSlug: "ringsted-by",
        authorIndex: 0,
        mediaId: "media-erhverv",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 1,
      },
      {
        slug: "ringsted-festival-offentliggoer-de-foerste-hovednavne-til-anlaegget",
        titel: "Ringsted Festival løfter sløret for sommerens program: Store danske navne på plakaten",
        manchet: "Billetsalget er gået i gang til festen i Lystanlægget, der sidste år meldte udsolgt på rekordtid.",
        sectionSlug: "musik",
        areaSlug: "ringsted-by",
        authorIndex: 1,
        mediaId: "media-kultur",
        pinned: false,
        breaking: true,
        indholdstype: "Uafhængig",
        daysAgo: 0,
        hoursAgo: 1,
      },
      {
        slug: "tms-ringsted-kaemper-for-overlevelse-i-herreligaen",
        titel: "TMS Ringsted henter heroisk uafgjort mod tophold i Dansk Kabel TV Arena",
        manchet: "Med en scoring i sidste sekund sikrede TMS sig et uundværligt point i kampen for at undgå nedrykningsspillet.",
        sectionSlug: "haandbold",
        areaSlug: "ringsted-by",
        authorIndex: 1,
        mediaId: "media-sport",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 2,
      },
      {
        slug: "kvaerkeby-fuglereservat-aabner-nyt-observationsskjul-for-skoleklasser",
        titel: "Kværkeby Fuglereservat indvier handicapvenligt fugletårn og naturrum",
        manchet: "Området rummer over 120 registrerede fuglearter og modtager nu støtte fra Friluftsrådet til formidling.",
        sectionSlug: "natur-og-klima",
        areaSlug: "kvaerkeby",
        authorIndex: 1,
        mediaId: "media-natur",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 3,
      },
      {
        slug: "benloese-faar-ny-multibane-og-aktivitetspark-for-unge",
        titel: "Unge i Benløse fejrer ny aktivitetspark: 'Her har vi manglet et sted at mødes'",
        manchet: "Parken kombinerer streetfodbold, bordtennis og opholdszoner og er opført i samarbejde med lokale unge.",
        sectionSlug: "idraetsforeninger",
        areaSlug: "benloese",
        authorIndex: 0,
        mediaId: "media-forening",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 4,
      },
      {
        slug: "midt-sjaellands-toemrerfirma-vinder-pris-for-laerlingeforloeb",
        titel: "Lokal tømrervirksomhed kåret for ekstraordinær indsats for unges erhvervsuddannelse",
        manchet: "Virksomheden i Høm har uddannet over 20 lærlinge på ti år og sikrer høj faglig stolthed.",
        sectionSlug: "job-og-arbejdsmarked",
        areaSlug: "hoem",
        authorIndex: 0,
        mediaId: "media-erhverv",
        pinned: false,
        breaking: false,
        indholdstype: "Partner",
        marking: {
          sponsor: "Ringsted Erhvervsråd",
          labelTekst: "Finansieret af Ringsted Erhvervsråd",
          aftaleId: "sa-ringsted-erhverv",
        },
        daysAgo: 5,
      },
      {
        slug: "overblik-det-besluttede-ringsted-byraad-om-kollektiv-trafik",
        titel: "Dagens overblik: Ringsted Byråd bevarer busruter til oplandets landsbyer",
        manchet: "Trods sparekrav er der fundet finansiering til at opretholde afgangene mellem Jystrup, Vigersted og Ringsted Station.",
        sectionSlug: "trafik",
        areaSlug: "ringsted-by",
        authorIndex: 0,
        mediaId: "media-byraad",
        pinned: false,
        breaking: false,
        indholdstype: "AI-assisteret",
        marking: {
          godkendtAf: "Henrik Bang",
          kilder: [
            "https://ringsted.dk/dagsordener-og-referater/byraad/2026-09",
            "Movia og Ringsted Kommune Trafikudvalg",
          ],
        },
        hasQuoteWithSource: true,
        daysAgo: 0,
        hoursAgo: 10,
      },
      {
        slug: "debat-ringsted-er-sjaellands-logistiske-hjerte-lad-os-udnytte-det",
        titel: "Kommentar: Ringsteds placering som jernbaneknudepunkt forpligter til mere ambitiøs byudvikling",
        manchet: "Når Femern-forbindelsen åbner, bliver Ringsted endnu mere central. Vi skal være klar med boliger og arbejdspladser.",
        sectionSlug: "kommentarer",
        areaSlug: "ringsted-by",
        authorIndex: 0,
        mediaId: "media-debat",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        debatLabel: "Kommentar",
        daysAgo: 6,
      },
      {
        slug: "indsendt-jystrup-forsamlingshus-holder-hoestmarked",
        titel: "Fra borgerne: Lokalt høstmarked i Jystrup med æblemostning og kunsthåndværk",
        manchet: "Borgere opfordres til at medbringe egne æbler til fællesmosteren og smage lokalt bagværk på søndag.",
        sectionSlug: "frivillige",
        areaSlug: "jystrup",
        authorIndex: 1,
        mediaId: "media-natur",
        pinned: false,
        breaking: false,
        indholdstype: "Brugerindsendt",
        marking: {
          afsender: "Jystrup Kultur- og Forsamlingshus",
        },
        daysAgo: 8,
      },
    ],
  },

  // ─── 4. KØGE ────────────────────────────────────────────────────────────
  {
    id: "koege-site",
    navn: "KøgeLokalt",
    domaene: "koegelokalt.dk",
    kommune: "Køge",
    tagline: "Lokaljournalistik med blik for Køges vækst, havn og stærke fællesskaber",
    colors: {
      accent: "#24533A", // Skov
      accentStrong: "#183B29",
      accentSoft: "#D5E7DD",
      onAccent: "#FFFFFF",
    },
    sideTekster: {
      omMediet:
        "KøgeLokalt leverer uafhængig nyhedsformidling om erhvervslivet, den historiske bykerne, stationsbyerne og det store udviklingsområde i Køge Kyst og Køge Nord.",
      principper:
        "Vores redaktionelle linje er fri og ubundet. Vi følger Pressenævnets retningslinjer til punkt og prikke.",
      kontakt:
        "Kontakt redaktionen på redaktion@koegelokalt.dk eller telefon 56 60 00 00.",
    },
    areas: [
      { navn: "Køge By", slug: "koege-by", lat: 55.4583, lng: 12.1822 },
      { navn: "Køge Nord", slug: "koege-nord", lat: 55.495, lng: 12.17 },
      { navn: "Herfølge", slug: "herfoelge", lat: 55.4131, lng: 12.1469 },
      { navn: "Borup", slug: "borup", lat: 55.4967, lng: 11.975 },
      { navn: "Ejby", slug: "ejby", lat: 55.4908, lng: 12.0833 },
      { navn: "Bjæverskov", slug: "bjaeverskov", lat: 55.4572, lng: 12.0306 },
      { navn: "Vemmedrup", slug: "vemmedrup", lat: 55.4667, lng: 12.0889 },
      { navn: "Algestrup", slug: "algestrup", lat: 55.3789, lng: 12.0833 },
    ],
    authors: [
      {
        id: "author-koege-christian",
        navn: "Christian Møller",
        slug: "christian-moeller",
        type: "Fast",
        bio: "Ledende redaktør på KøgeLokalt med baggrund i erhvervs- og transportjournalistik.",
        avatar: "/avatars/carsten.svg",
        email: "redaktoer@koege.test",
      },
      {
        id: "author-koege-sara",
        navn: "Sara Kirkegaard",
        slug: "sara-kirkegaard",
        type: "Fast",
        bio: "Byudviklings- og kulturreporter med fingeren på pulsen i Køge Kyst og midtbyen.",
        avatar: "/avatars/rikke.svg",
        email: "sara@koege.test",
      },
      {
        id: "author-koege-thomas",
        navn: "Thomas Bro",
        slug: "thomas-bro",
        type: "Freelance",
        bio: "Sportsjournalist og lokalskribent med særligt fokus på Herfølge Boldklub og foreningsliv.",
        avatar: "/avatars/jonas.svg",
        email: "journalist@koege.test",
      },
    ],
    organizations: [
      {
        id: "org-koege-erhverv",
        navn: "Køge Erhvervsforening",
        branche: "Erhvervsforening",
        kontakt: "kontakt@koegeerhverv.dk",
        aftaleId: "sa-koege-erhverv",
        aftalePris: 30000,
      },
    ],
    articles: [
      {
        slug: "koege-kyst-nye-bykvarterer-forener-havn-og-strand-med-bykernen",
        titel: "Køge Kysts vision tager form: Nyt brokvarter binder den gamle bymidte sammen med havet",
        manchet: "Det store byudviklingsprojekt leverer nye grønne almindinger, bæredygtige boliger og plads til lokale butikker.",
        sectionSlug: "bolig-og-byudvikling",
        areaSlug: "koege-by",
        authorIndex: 1,
        mediaId: "media-havn",
        pinned: true,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 0,
        hoursAgo: 2,
      },
      {
        slug: "koege-nord-station-slaar-passagerrekord-som-sjaellands-groenne-knudepunkt",
        titel: "Køge Nord Station runder 1,5 millioner rejsende: 'Pendlere vælger toget frem for motorvejskøen'",
        manchet: "Kombinationen af højhastighedsbane og S-tog gør stationen til et af landets mest succesfulde infrastrukturanlæg.",
        sectionSlug: "trafik",
        areaSlug: "koege-nord",
        authorIndex: 0,
        mediaId: "media-trafik",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 1,
      },
      {
        slug: "herfoelge-boldklub-fejrer-100-aars-jubilaeum-med-kaempestor-byfest",
        titel: "Herfølge Boldklub runder 100 år: Fejrer guld-triumfen fra 2000 og det stærke fællesskab",
        manchet: "Tidligere mestre og nuværende ungdomshold samles til opvisningskamp og fællesspisning på Herfølge Stadion.",
        sectionSlug: "fodbold",
        areaSlug: "herfoelge",
        authorIndex: 2,
        mediaId: "media-sport",
        pinned: false,
        breaking: true,
        indholdstype: "Uafhængig",
        daysAgo: 0,
        hoursAgo: 1,
      },
      {
        slug: "kjoege-mini-by-udvider-med-fem-nye-historiske-modeller",
        titel: "Kjøge Mini-By udvider: Frivillige håndværkere genskaber 1800-tallets bindingsværkshuse",
        manchet: "Over 80 frivillige pensionister og entusiaster har lagt tusindvis af timer i de historisk korrekte miniaturebygninger.",
        sectionSlug: "kunst-og-museer",
        areaSlug: "koege-by",
        authorIndex: 1,
        mediaId: "media-kultur",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 2,
      },
      {
        slug: "borup-erhvervsforening-lancerer-kampagne-for-lokalt-handelsliv",
        titel: "Borup står sammen: Ny kampagne skal styrke butikslivet i stationsbyen",
        manchet: "Handlende og foreninger lancerer fælles kundekort og månedlige torvedage for at holde handlen i byen.",
        sectionSlug: "handel",
        areaSlug: "borup",
        authorIndex: 0,
        mediaId: "media-erhverv",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 3,
      },
      {
        slug: "bjaeverskov-faar-ny-cykelsti-til-ejby-forbedrer-skolevejen",
        titel: "Efter ti års ventetid: Ny asfalteret cykelsti forbinder Bjæverskov og Ejby",
        manchet: "Børn og motionister slipper nu for at cykle på den stærkt trafikerede landevej.",
        sectionSlug: "skole-og-boern",
        areaSlug: "bjaeverskov",
        authorIndex: 2,
        mediaId: "media-skole",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 4,
      },
      {
        slug: "koege-marina-investerer-i-groen-havneinfrastruktur",
        titel: "Køge Marina installerer ladefaciliteter til el-både og moderne spildevandsanlæg",
        manchet: "Som en af Danmarks største lystbådehavne går Køge forrest i omstillingen til miljøvenlig sejlsport.",
        sectionSlug: "byggeri-og-ejendomme",
        areaSlug: "koege-by",
        authorIndex: 0,
        mediaId: "media-havn",
        pinned: false,
        breaking: false,
        indholdstype: "Partner",
        marking: {
          sponsor: "Køge Erhvervsforening",
          labelTekst: "Finansieret af Køge Erhvervsforening",
          aftaleId: "sa-koege-erhverv",
        },
        daysAgo: 5,
      },
      {
        slug: "overblik-koege-byraads-beslutninger-om-erhvervshavnen",
        titel: "Dagens overblik: Køge Byråd godkender lokalplan for udvidelse af Skandinavisk Transport Center",
        manchet: "Gennemgang af byrådets godkendelse af nye logistikarealer og skærpede miljøkrav til godstransport.",
        sectionSlug: "politik",
        areaSlug: "koege-by",
        authorIndex: 0,
        mediaId: "media-byraad",
        pinned: false,
        breaking: false,
        indholdstype: "AI-assisteret",
        marking: {
          godkendtAf: "Christian Møller",
          kilder: [
            "https://koege.dk/politik/byraad/referater-2026",
            "Køge Kommune Plan- og Miljøudvalg",
          ],
        },
        hasQuoteWithSource: true,
        daysAgo: 0,
        hoursAgo: 9,
      },
      {
        slug: "debat-koege-skal-vaere-forgangsby-for-baeredygtig-byudvikling",
        titel: "Leder: Byvækst og natur i balance: Vi må ikke glemme Køges grønne åndehuller",
        manchet: "Køge oplever landets højeste tilflytning. Det kræver politisk mod at værne om ådalen og de kystnære strandenge.",
        sectionSlug: "leder",
        areaSlug: "koege-by",
        authorIndex: 0,
        mediaId: "media-debat",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        debatLabel: "Leder",
        daysAgo: 6,
      },
      {
        slug: "indsendt-vemmedrup-borgerforening-soeger-frivillige-til-bypark",
        titel: "Fra borgerne: Arbejdsdag i Vemmedrup Bypark — hjælp med at bygge insekthoteller",
        manchet: "Lørdag formiddag mødes vi ved søen med kaffe og kage for at klargøre parken og stierne til sommeren.",
        sectionSlug: "frivillige",
        areaSlug: "vemmedrup",
        authorIndex: 2,
        mediaId: "media-natur",
        pinned: false,
        breaking: false,
        indholdstype: "Brugerindsendt",
        marking: {
          afsender: "Vemmedrup Borgerforening",
        },
        daysAgo: 7,
      },
    ],
  },

  // ─── 5. ROSKILDE ────────────────────────────────────────────────────────
  {
    id: "roskilde-site",
    navn: "RoskildeLokalt",
    domaene: "roskildelokalt.dk",
    kommune: "Roskilde",
    tagline: "Kultur, viden og byens puls — uafhængig lokaljournalistik i Roskilde",
    colors: {
      accent: "#6A3553", // Lyng
      accentStrong: "#4F263D",
      accentSoft: "#EEDEE7",
      onAccent: "#FFFFFF",
    },
    sideTekster: {
      omMediet:
        "RoskildeLokalt dækker Danmarks musikhovedstad, universitetet, fjorden og lokalsamfundene fra Jyllinge til Viby Sjælland.",
      principper:
        "Vores nyhedsdækning er faktabaseret og uafhængig af kommunale og kommercielle aktører.",
      kontakt:
        "Kontakt redaktionen på redaktion@roskildelokalt.dk eller telefon 46 30 00 00.",
    },
    areas: [
      { navn: "Roskilde By", slug: "roskilde-by", lat: 55.6415, lng: 12.0803 },
      { navn: "Trekroner", slug: "trekroner", lat: 55.6517, lng: 12.1333 },
      { navn: "Jyllinge", slug: "jyllinge", lat: 55.7539, lng: 12.1028 },
      { navn: "Viby Sjælland", slug: "viby-sjaelland", lat: 55.5492, lng: 12.0042 },
      { navn: "Svogerslev", slug: "svogerslev", lat: 55.6361, lng: 12.0153 },
      { navn: "Vindinge", slug: "vindinge", lat: 55.6178, lng: 12.1389 },
      { navn: "Gundsømagle", slug: "gundsoemagle", lat: 55.7347, lng: 12.1528 },
      { navn: "Gadstrup", slug: "gadstrup", lat: 55.5722, lng: 12.0736 },
    ],
    authors: [
      {
        id: "author-roskilde-louise",
        navn: "Louise Windeløv",
        slug: "louise-windeloev",
        type: "Fast",
        bio: "Chefredaktør på RoskildeLokalt med særligt fokus på kulturpolitik og byens vækst.",
        avatar: "/avatars/rikke.svg",
        email: "redaktoer@roskilde.test",
      },
      {
        id: "author-roskilde-frederik",
        navn: "Frederik Holm",
        slug: "frederik-holm",
        type: "Fast",
        bio: "Politisk reporter og RUC-korrespondent med base i Trekroner og Rådhuset.",
        avatar: "/avatars/carsten.svg",
        email: "frederik@roskilde.test",
      },
      {
        id: "author-roskilde-julie",
        navn: "Julie Secher",
        slug: "julie-secher",
        type: "Freelance",
        bio: "Kultur- og musikjournalist med dækning af Musicon, Roskilde Festival og fjordlivet.",
        avatar: "/avatars/mette.svg",
        email: "journalist@roskilde.test",
      },
    ],
    organizations: [
      {
        id: "org-roskilde-kulturfond",
        navn: "Roskilde Kulturfond",
        branche: "Kultur og fonde",
        kontakt: "fond@roskildekultur.dk",
        aftaleId: "sa-roskilde-kulturfond",
        aftalePris: 30000,
      },
    ],
    articles: [
      {
        slug: "musicon-kreativ-bydel-fejrer-aabning-af-nyt-kulturhus-og-skatehal",
        titel: "Musicon fuldender sin kreative akse: Nyt kulturhus og skaterum åbner dørene",
        manchet: "Den forhenværende betonfabrik i Roskilde Syd er blevet et internationalt forbillede for levende og uortodoks byudvikling.",
        sectionSlug: "kunst-og-museer",
        areaSlug: "roskilde-by",
        authorIndex: 0,
        mediaId: "media-kultur",
        pinned: true,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 0,
        hoursAgo: 2,
      },
      {
        slug: "roskilde-fjord-nyt-digeanlaeg-i-jyllinge-nordmark-bestaar-foerste-test",
        titel: "Jyllinge Nordmark sikret mod stormflod: Kystsikring til 100 millioner kroner består prøven",
        manchet: "Pumper og diger holdt vandmasserne ude under nattens kraftige blæst i Roskilde Fjord.",
        sectionSlug: "natur-og-klima",
        areaSlug: "jyllinge",
        authorIndex: 1,
        mediaId: "media-natur",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 1,
      },
      {
        slug: "trekroner-ruc-studerende-og-lokale-ivaerksaettere-danner-nyt-innovationsfaellesskab",
        titel: "Trekroner Hub: RUC-forskere og lokale tech-virksomheder går sammen om grøn innovation",
        manchet: "Et nyt kontorfællesskab ved Trekroner Station skal bygge bro mellem universitetets viden og det sjællandske erhvervsliv.",
        sectionSlug: "ivaerksaettere",
        areaSlug: "trekroner",
        authorIndex: 1,
        mediaId: "media-erhverv",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 2,
      },
      {
        slug: "roskilde-festival-donerer-15-millioner-til-lokale-kultur-og-ungdomsprojekter",
        titel: "Roskilde Festival uddeler 15 millioner i overskud: 'Frivilligheden er vores hjerteblod'",
        manchet: "Over 40 lokale foreninger og sociale initiativer modtager støtte fra festivalens fond i år.",
        sectionSlug: "musik",
        areaSlug: "roskilde-by",
        authorIndex: 2,
        mediaId: "media-kultur",
        pinned: false,
        breaking: true,
        indholdstype: "Uafhængig",
        daysAgo: 0,
        hoursAgo: 1,
      },
      {
        slug: "fc-roskilde-henter-point-i-dramatisk-slutspurt-i-2-division",
        titel: "FC Roskilde sikrer dramatisk uafgjort foran 1.900 tilskuere i Idrætsparken",
        manchet: "To mål i de sidste ti minutter udløste jubelscener blandt de trofaste fans i den traditionsrige ørn-klub.",
        sectionSlug: "fodbold",
        areaSlug: "roskilde-by",
        authorIndex: 2,
        mediaId: "media-sport",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 3,
      },
      {
        slug: "viby-sjaelland-faar-ny-groen-bymidte-med-torv-og-lokalhandel",
        titel: "Viby Sjælland indvier nyt torv: 'Stationsbyerne skal have deres egne samlingssteder'",
        manchet: "Borgere og politikere klippede snoren til et nyt bytorv med grønne opholdszoner og ladestandere.",
        sectionSlug: "bolig-og-byudvikling",
        areaSlug: "viby-sjaelland",
        authorIndex: 1,
        mediaId: "media-byraad",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        daysAgo: 4,
      },
      {
        slug: "roskilde-domkirke-investerer-i-baeredygtig-klimastyring-af-kulturarven",
        titel: "UNESCO-klenodiet Roskilde Domkirke tester nyt geotermisk klimaanlæg til beskyttelse af kongegravene",
        manchet: "Moderne sensorer og grøn energi sikrer, at de uvurderlige kalkmalerier og sarkofager bevares for eftertiden.",
        sectionSlug: "kunst-og-museer",
        areaSlug: "roskilde-by",
        authorIndex: 0,
        mediaId: "media-kultur",
        pinned: false,
        breaking: false,
        indholdstype: "Partner",
        marking: {
          sponsor: "Roskilde Kulturfond",
          labelTekst: "Finansieret af Roskilde Kulturfond",
          aftaleId: "sa-roskilde-kulturfond",
        },
        daysAgo: 5,
      },
      {
        slug: "overblik-det-besluttede-roskilde-byraad-om-klimaneutralitet-i-2030",
        titel: "Dagens overblik: Roskilde Byråd vedtager bindende køreplan mod CO2-neutralitet",
        manchet: "Kommunen skal udfase fossil opvarmning i samtlige kommunale bygninger og udvide fjernvarmenettet til Svogerslev.",
        sectionSlug: "politik",
        areaSlug: "roskilde-by",
        authorIndex: 1,
        mediaId: "media-byraad",
        pinned: false,
        breaking: false,
        indholdstype: "AI-assisteret",
        marking: {
          godkendtAf: "Louise Windeløv",
          kilder: [
            "https://roskilde.dk/politik/byraad/2026-09-klimaplan",
            "Roskilde Byråds Klimasekretariat",
          ],
        },
        hasQuoteWithSource: true,
        daysAgo: 0,
        hoursAgo: 11,
      },
      {
        slug: "debat-roskilde-skal-turde-stille-krav-til-de-store-kulturinstitutioner",
        titel: "Leder: Musikhovedstaden skal også huske hverdagen i forstæderne",
        manchet: "Roskilde bruger mange midler på fyrtårne. Vi må ikke tabe skolerne i Gundsømagle og idrætslivet i Gadstrup af syne.",
        sectionSlug: "leder",
        areaSlug: "roskilde-by",
        authorIndex: 0,
        mediaId: "media-debat",
        pinned: false,
        breaking: false,
        indholdstype: "Uafhængig",
        debatLabel: "Leder",
        daysAgo: 6,
      },
      {
        slug: "indsendt-svogerslev-lokalraad-efterlyser-gamle-fotos-til-byarkiv",
        titel: "Fra borgerne: Svogerslev samler ind til digitalt lokalhistorisk fotoarkiv",
        manchet: "Ligger du inde med gamle fotos af byens købmand eller gadekæret? Mød op på biblioteket tirsdag aften.",
        sectionSlug: "lokalraad",
        areaSlug: "svogerslev",
        authorIndex: 2,
        mediaId: "media-forening",
        pinned: false,
        breaking: false,
        indholdstype: "Brugerindsendt",
        marking: {
          afsender: "Svogerslev Lokalhistoriske Forening",
        },
        daysAgo: 7,
      },
    ],
  },
];
